//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH05.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.SqlServer;
    
    public partial class AdminUser
    {
        [Required(ErrorMessage ="Mã không để trống")]
        [Display(Name ="Mã User")]
        public int ID { get; set; }
        [Required(ErrorMessage ="Name not emty ...")]
        [Display(Name ="Tên User")]
        public string NameUser { get; set; }
        [Display(Name ="Vị trí")]
        public string RoleUser { get; set; }
        [Display(Name ="PassWord")]
        [Required(ErrorMessage ="Pass not emty...")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }
        [NotMapped]
        [Compare("PasswordUser")]
        [Display(Name ="Nhập lại mật khẩu")]

        public string ConfimPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}
